#ifndef _MP_ERROR_CODES_H_
#define _MP_ERROR_CODES_H_

#define MP_SUCCESS 0
#define MP_INVALID_ARGUMENTS -1
#define MP_FILE_NOT_FOUND -2
#define MP_UNSUCESSFULL_INIT -3
#define MP_CORRUPTED_FILE -4
#define MP_INVALID_COMMAND -5
#define MP_FILE_LIMIT_EXCEED -6
#define MP_NOT_WAV_FILE -7
#define MP_SEEK_OVERFLOW -8
#define MP_SEEK_UNDERFLOW -9
#define MP_VOLUME_BEYOND_LIMIT -10
#define MP_VOLUME_UNDERFLOW -11
#define MP_PLAYBACK_THREAD_NOT_ALLOWED -12
#define MP_STOP_ERROR -13
#define MP_PAUSE_ERROR -14
#define MP_RESUME_ERROR -15
#define MP_NEXT_TRACK_ERROR -16 
#define MP_PREVIOUS_TRACK_ERROR -17
#define MP_STATE_CHANGE_FAILURE -18

#endif
